name: 'Docker Build'

on:
  push:
    tags:
      - '**'
#    branches:
#      - 'yourbranch' # may be useful for testing

env:
  latest_tag: "${{ github.ref_type == 'tag' && ',docker.io/vshn/k8ify:latest' || '' }}"

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=true # Without this the .git directory is not present and our tests fail
          push: true
          tags: "docker.io/vshn/k8ify:${{ github.ref_name }}${{ env.latest_tag }}"
